<!--1.Reyes españoles (dtd_15.xml)-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reyesEspañoles [
  <!ELEMENT reyesEspañoles ((rey|reina)*)>
  <!ELEMENT rey (nombre, padre, madre)>
  <!ELEMENT reina (nombre, padre, madre)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT padre (#PCDATA)>
  <!ELEMENT madre (#PCDATA)>
]>

<reyesEspañoles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    <reina>
        <nombre>Juana la Loca</nombre>
        <padre>Fernando el Católico</padre>
        <madre>Isabel la Católica</madre>
    </reina>
    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe el Hermoso</padre>
        <madre>Juan la Loca</madre>
    </rey>
</reyesEspañoles>

<!--2.Países (dtd_16.xml)-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
  <!ELEMENT paises (pais*)>
  <!ELEMENT pais (nombre, unionEuropea?, otan?)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT unionEuropea EMPTY>
  <!ELEMENT otan EMPTY>
]>

<paises>
  <pais>
    <nombre>España</nombre>
    <unionEuropea />
    <otan />
  </pais>
  <pais>
    <nombre>Noruega</nombre>
    <otan />
  </pais>
  <pais>
    <nombre>Austria</nombre>
    <unionEuropea />
  </pais>
</paises>

<!--1.Datos personales (dtd_31.xml)-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona [
  <!ELEMENT persona EMPTY>
  <!ATTLIST persona nombre CDATA #IMPLIED>
]>

<persona />

<!--2.Película (dtd_32.xml)-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula [
  <!ELEMENT pelicula EMPTY>
  <!ATTLIST pelicula titulo CDATA #IMPLIED>
]>

<pelicula titulo="La diligencia" />

<!--3.Cuadros (dtd_33.xml)-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cuadros [
  <!ELEMENT cuadros (cuadro*)>
  <!ELEMENT cuadro EMPTY>
  <!ATTLIST cuadro titulo ID #REQUIRED>
  <!ATTLIST cuadro autor CDATA #REQUIRED>
]>

<cuadros>
  <cuadro titulo="Adán_y_Eva_1" autor="Alberto Durero" />
  <cuadro autor="Lucas Cranach, el viejo" titulo="Adán_y_Eva_2" />
</cuadros>

<!--