=== Nightmarehxc/practicasDAM/2Trimestre/LenguajedeMarcas/ExamenDcamarero/question1/dtdext.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_de_notas [
        <!ELEMENT lista_de_notas (nota)*>
        <!ELEMENT nota (nota_dia|para|de|titulo|contenido)*>
        <!ELEMENT nota_dia (#PCDATA)>
        <!ATTLIST  nota_dia (par|impar) #PCDATA default-value)>
        <!ELEMENT para (#PCDATA)>
        <!ELEMENT de (#PCDATA)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT contenido (#PCDATA)>
        ]>

=== Nightmarehxc/practicasDAM/2Trimestre/LenguajedeMarcas/ExamenDcamarero/question1/cuestion1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "dtdext.dtd">
<lista_de_notas>
    <nota>
        <nota_dia="impar">
        <para>Pedro</para>
        <de>Laura</de>
        <titulo>Recordatorio</titulo>
        <contenido>A las 7:00 pm en la puerta del teatro</contenido>
        </nota_dia>
    </nota>
    <nota>
    <nota_dia="par">
        <para>Pedro</para>
        <de>Juan</de>
        <titulo>Informes</titulo>
        <contenido>Te he dejado los informes en el casillero</contenido>
        </nota_dia>
    </nota>
</lista_de_notas>
